name: Check

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    steps:
      - name: 检出代码
        uses: actions/checkout@v6.0.2

      - name: 获取信息
        id: get
        env:
          QB_REPO: qbittorrent/qBittorrent
          QB_BR: v4_1_x
          LT_REPO: arvidn/libtorrent
          LT_BR: RC_1_1
        run: |
          qb_sha=$(gh api "/repos/$QB_REPO/commits/$QB_BR" -q '.sha')
          lt_sha=$(gh api "/repos/$LT_REPO/commits/$LT_BR" -q '.sha')
          echo "cache=$qb_sha-$lt_sha" >>"$GITHUB_OUTPUT"

      - name: 缓存校验
        id: cache
        uses: actions/cache@v5.0.4
        with:
          path: .cache
          key: ${{ steps.get.outputs.cache }}

      - name: 触发工作流
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          >.cache
          gh workflow run Build
