name: Check

on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 获取信息
        id: get
        env:
          QB_SRC: qbittorrent/qBittorrent
          QB_VER: v4_1_x
          LT_SRC: arvidn/libtorrent
          LT_VER: RC_1_1
        run: |
          qb_sha=$(gh api "/repos/$QB_SRC/commits/$QB_VER" -q '.sha')
          lt_sha=$(gh api "/repos/$LT_SRC/commits/$LT_VER" -q '.sha')

          printf '%s\n' "key=$qb_sha-$lt_sha" >>"$GITHUB_OUTPUT"

      - name: 缓存校验
        id: cache
        uses: actions/cache@v5
        with:
          path: .cache
          key: ${{ steps.get.outputs.key }}

      - name: 触发工作流
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          [[ -f .cache ]] || touch .cache
          gh workflow run Build
